// <auto-generated />
using InventoryTrackingAutomation.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InventoryTrackingAutomation.Migrations
{
    [DbContext(typeof(InventoryTrackingAutomationDbContext))]
    [Migration("20260629123026_Optimization_Lookups_SoftDelete")]
    partial class Optimization_Lookups_SoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
        }
    }
}
