<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>InventoryTrackingAutomation</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.3.0" />
    <PackageReference Include="SystemStandards.Core" Version="2.0.0" />
    <ProjectReference Include="..\InventoryTrackingAutomation.Application.Contracts\InventoryTrackingAutomation.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
